latest update

diff --git a/.github/workflows/run-tests.yaml b/.github/workflows/run-tests.yaml
--- a/.github/workflows/run-tests.yaml
+++ b/.github/workflows/run-tests.yaml
@@ -1,11 +1,11 @@
 name: Run Test
 
 on:
-  workflow_call:
-    outputs:
-      docker_tag:
-        description: "Docker Tag"
-        value: ${{ jobs.build_docker.outputs.docker_tag }}
+  workflow_call
+#    outputs:
+#      docker_tag:
+#        description: "Docker Image Tag"
+#        value: ${{ jobs.build_docker.outputs.docker_tag }}
 
 jobs:
   build_docker:
@@ -17,41 +17,18 @@ jobs:
     name: Run Tests
     runs-on: ubuntu-latest
     needs: build_docker
-
-    steps:
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
-
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
-
-      - name: Decode Docker Tag
-          id: decode_tag
-          uses: cloudposse/github-action-secret-outputs@main
-          with:
-            secret: ${{ secrets.PASSWORD }}
-            op: decode
-            in: ${{ needs.build_docker.outputs.docker_tag }}
-
-            - name: Retrieve Docker Tag from Previous Job
-              run: |
-                echo "HERE IS THE DOCKER TAG: ${{ steps.decode_tag.outputs.out }}"
-
-            - name: Pull and Run Docker Image
-              run: |
-                DOCKER_TAG="${{ steps.decode_tag.outputs.out }}"
-                echo "Pulling Docker Image: $DOCKER_TAG"
-                docker pull $DOCKER_TAG
-                docker run -d --name test_container $DOCKER_TAG
+    container:
+      image: ${{ needs.build_docker.outputs.docker_tag }}
+      credentials:
+        username: ${{ vars.username }}
+        password: ${{ secrets.hybrid_learning_hub_app }}
+      defaults:
+        run:
+          working-directory: /backend
 
       services:
         postgres:
-          image: postgis/postgis:13-3.1
+          image: postgis/postgis:14
           options: >-
             --health-cmd "pg_isready"
             --health-interval 1s
@@ -60,5 +37,18 @@ jobs:
           env:
             POSTGRES_PASSWORD: postgres
 
-        redis:
-          image: redis:5.0-buster
+#        redis:
+#          image: redis:5.0-buster
+
+      steps:
+#        - name: OPenAPI
+#          run: openapi-spec-validator-docs/openapi/xxx.yaml
+#          name: Parliament
+#          if: ${{ success() || failure() }}
+#          run: parliament --directory /xxx/xxx/ --config .parlia-config.yaml
+        - name: Pytest
+          run: >
+            dotenv --file ops/test-variables.env
+            run /bin/bash -c
+            "pytest tests/functional --cov xxx --cov-report term-missing --durations=28"
+        
